Repository KnapsackPro/knapsack-pro-cypress, pull requests merged in 2023-01, with the labels that each got.

#85 Support env KNAPSACK_PRO_TEST_FILE_EXCLUDE_PATTERN
  package-lock.json
  package.json
  src/env-config.ts
  src/test-files-finder.ts
Labels: enhancement

#86 Improvements: make project compile again
  README.md
  package-lock.json
  package.json
  src/test-files-finder.ts
Labels: bug

#87 Update @knapsack-pro/core to 3.3.1
  package-lock.json
  package.json
Labels: enhancement, dependencies

#88 Search for test files on the disk only if needed by the `@knapsack-pro/core`
  package-lock.json
  package.json
  src/knapsack-pro-cypress.ts
Labels: bug, dependencies
